# Generated by Django 3.0.6 on 2020-06-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200604_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.CharField(default='alex', max_length=100),
        ),
    ]
